# 开发环境配置
server:
  port: 8180
# Spring配置
spring:
  profiles:
    active: druid
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /

#token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌有效期（默认30分钟）
  expireTime: 0
  # 密钥
  key: 12345_ssdlh_lhbcf_zcdhd_cmbjx_ccwtn_ylfys_hlzds

# MyBatis配置
mybatis-plus:
  # 搜索指定包别名
  typealiasespackage: com.lemonyangzw.stusystem.project.*.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
  # 加载全局的配置文件
  config-Location: classpath:mybatis/mybatis-config.xml
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: "2"
      logic-not-delete-value: "0"

  # redis 配置
redis:
  # 地址
  host: localhost
  # 端口，默认为6379
  port: 6379
  # 密码
  password:
  # 连接超时时间
  timeout: 10s
  lettuce:
    pool:
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池的最大数据库连接数
      max-active: 8
      # #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1ms

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 日志配置
logging:
  level:
    com.lemonyangzw.stusystem: debug
    org.springframework: warn