# 开发环境配置
server:
  port: 8180
# Spring配置
spring:
  profiles:
    active: druid

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /

#token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌有效期（默认30分钟）
  expireTime: 30
  # 密钥
  key : 12345_ssdlh_lhbcf_zcdhd_cmbjx_ccwtn_ylfys_hlzds

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typealiasespackage: com.lemonyangzw.stusystem.project.*.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
  # 加载全局的配置文件
  config-Location: classpath:mybatis/mybatis-config.xml

